# your-repo/.github/workflows/reuse-build-publish.yml

name: Reuse Build and Publish to GHCR

on:
  push:
    branches: [main, release, develop]
  pull_request:

jobs:
  build-and-publish:
    uses: kakaotech-19/.github/.github/workflows/build-and-publish-ghcr.yml@main
    with:
      registry_username: ${{ secrets.ORGANIZATION }} # or your GitHub username
      registry_password: ${{ secrets.PAT_TOKEN }}
      discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
      repository_name: ${{ github.repository }}
    secrets:
      ORGANIZATION: ${{ secrets.ORGANIZATION }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
